version: "3"

services:
  web:
    build: .
    expose:
      - "8000"
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always